### ISSUE TITLE
Mina upgrade to 1.0

### ISSUE THREAD

**Issue by windy** [80percent/rails-template#12]

**Comment by ghost** [comment]
mina 1.0 released

**Comment by windy** [comment]
It's time to resolve this issue.

**Comment by dimosz** [comment]
@windy 
不知道升级后，这个问题能不能得到解决：[issue](https://github.com/Mic92/mina-sidekiq/issues/4)

**Comment by ghost** [comment]
@windy 
mina 升级到 1.0，deploy.rb 中内容不用专门针对 mina 1.0 做升级吗？

**Comment by windy** [comment]
@dimosz 嗯, 需要, 现在正在实际项目中验证.

**Comment by windy** [comment]
@dimosz 做了一些修改, 已经实际使用中.

**Comment by ghost** [comment]
@windy 按照你这个将 mina 升级到 1.0，却发现ssh 出了问题。我的服务器 ssh 端口不是默认的 22，但是升级后，使用mina 的命令，总是显示 `ssh: connect to host xxx port 22: Operation timed out`。升级前没问题，deploy.rb 中有 set :port 'xxxx'。这会是哪的问题呢？

**Comment by windy** [comment]
@dimosz  mina1.0 有点坑,  set port 需要放在 require 的后面才能生效.

**Comment by ghost** [comment]
@windy 果真是这样，Thanks
